module.exports = {
  siteTitle: 'Data Cup Web Site',
  siteTitleAlt: 'Data Cup',
  siteLogo: '/logos/logo-512x512.png',
  siteUrl: 'https://datacup.net',
  pathPrefix: '/',
  siteDescription: 'Find better leads with Data Cup.',
  siteRss: '/rss.xml',
  siteFBAppID: '',
  googleTagManagerID: '',
  userName: 'Data Cup',
  userTwitter: '#',
  userLocation: 'Berlin, Germany',
  userDescription: '',
  copyright: 'Copyright © Data Cup 2018. All Rights Reserved.',
  themeColor: '#00d1b2',
  backgroundColor: '#ffffff',
}
